//
// Created by Jeremy on 3/15/2017.
//

#ifndef VISUALINERTIALODOMETRY_ANDROID_UW_SAR_2_VOPOSE_H
#define VISUALINERTIALODOMETRY_ANDROID_UW_SAR_2_VOPOSE_H


class VOPose {

};


#endif //VISUALINERTIALODOMETRY_ANDROID_UW_SAR_2_VOPOSE_H
