//
// Created by Jeremy on 3/14/2017.
//

#ifndef VISUALINERTIALODOMETRY_ANDROID_UW_SAR_2_VIOCONSTANTS_H
#define VISUALINERTIALODOMETRY_ANDROID_UW_SAR_2_VIOCONSTANTS_H

static enum ERROR_CODE {
    INTEGER_OUT_OF_RANGE = 0
} VIOERROR;


#endif //VISUALINERTIALODOMETRY_ANDROID_UW_SAR_2_VIOCONSTANTS_H
