//
// Created by Jeremy on 3/14/2017.
//

#ifndef VISUALINERTIALODOMETRY_ANDROID_UW_SAR_2_VIOENGINE_H
#define VISUALINERTIALODOMETRY_ANDROID_UW_SAR_2_VIOENGINE_H


class VIOEngine {

};


#endif //VISUALINERTIALODOMETRY_ANDROID_UW_SAR_2_VIOENGINE_H
